### ISSUE TITLE
Some cities don't show weather related background imagein the Weather app

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/weather#50]
### Steps to reproduce
1. Open Weather app and click on a city.

### Expected behaviour
A background image that fits the weather should be shown.

### Actual behaviour
A black background shows up.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** Mysql 5.7

**PHP version:** 7.0

**Nextcloud version:**  12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Nextcloud 11

**Where did you install Nextcloud from:** Official updater

### Client configuration
**Browser:** Palemoon 27, Vivaldi 1.12

**Operating system:** Debian 9

#### Browser log
<details>
<summary>Browser log</summary>

```
TypeError: $scope.loadApiKey is not a function
Stack trace:
@https://server/apps/weather/js/app.js?v=becea38df1d73519905bb88fac044cff-1:65:26
f/q<@https://server/owncloud/apps/weather/js/angular.min.js?v=becea38df1d73519905bb88fac044cff-1:161:437
e@https://server/apps/weather/js/angular.min.js?v=becea38df1d73519905bb88fac044cff-1:48:146
pg/k.defer/c<@https://server/apps/weather/js/angular.min.js?v=becea38df1d73519905bb88fac044cff-1:51:68
 angular.min.js:123:209

TypeError: $scope.loadApiKey is not a function
Stack trace:
@https://server/apps/weather/js/app.js?v=becea38df1d73519905bb88fac044cff-1:65:26
f/q<@https://server/owncloud/apps/weather/js/angular.min.js?v=becea38df1d73519905bb88fac044cff-1:161:437
e@https://server/apps/weather/js/angular.min.js?v=becea38df1d73519905bb88fac044cff-1:48:146
pg/k.defer/c<@https://server/apps/weather/js/angular.min.js?v=becea38df1d73519905bb88fac044cff-1:51:68
 "Possibly unhandled rejection: {}"
```
</details>

**Comment by nerzhul** [comment]
hello, thanks for your report.
the JS problem seems to be unrelated, and should be fixed. Do you mean background is black because "overcast clouds" is not handled ?

**Comment by e-alfred** [comment]
Yes, the background is black for "overcast clouds". I later saw the JS bug come up most of the time, so it is probably unrelated.

**Comment by maxolasersquad** [comment]
I am seeing the same thing.

![image](https://user-images.githubusercontent.com/177150/52444507-931d4080-2af6-11e9-94bd-c31808e54e72.png)

**Comment by e-alfred** [comment]
I added more backgrounds in the latest releases, but some weather conditions might still not be covered. If you have some good pictures displaying weather conditions under a free license, please add them to the app with a PR.
